###
# @name userCreation
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "johndoe",
  "nickname": "john",
  "email": "john@example.com",
  "password": "Password123",
  "full_name": "John Doe",
  "avatar": "https://example.com/avatar.jpg"
}

###
# @name getUsers
GET http://localhost:3000/users


### 
# @name adminCreation
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "admin", 
  "nickname": "admin", 
  "email": "admin@gmail.com", 
  "password": "admin", 
  "full_name": "Admin Adminovich", 
"role": "admin"
}