###
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "john@example.com",
    "password": "1111"
}

###
# @name getProfile
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOiJkZGY5Y2NhNC1lNTJhLTRmN2YtYjdmMi01YWRmZWMwMzgwMzIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYzMjY3MCwiZXhwIjoxNzQ2NjMzMjcwfQ.3hqL-HhNNtQkwZ958o6mSNI5dplu8qOkXF3a95QwRcQ


###
# @name register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "mihail as",
  "nickname": "mik3",
  "email": "mik3@example.com",
  "password": "Password123"
}

###
# @name users
GET http://localhost:3000/users
